doctrine:
    dbal:
        driver: 'pdo_sqlite'
        path: '%kernel.project_dir%/var/data/sqlite.db'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Web/Entity'
                prefix: 'VDOLog\Web\Entity'
                alias: App
