parameters:
    locale: 'de'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'

    _instanceof:
        Twig\Extension\ExtensionInterface:
            tags: [ 'twig.extension' ]

    VDOLog\Web\:
        resource: '../src/Web/*'
        exclude: '../src/Web/{Model,Kernel.php}'

    VDOLog\Web\Controller\:
        resource: '../src/Web/Controller'
        tags: [ 'controller.service_arguments' ]

    VDOLog\Web\Model\ApplicationConfiguration:
        arguments:
            - ['%kernel.project_dir%/config/phpdesktop/settings.json', '%kernel.project_dir%/../settings.json']
